# write a program to input eight numbers from the user and display all the unique numbers(once)?

s = set()
s1 = int(input("enter first no."))
s.add(s1)
s2 = int(input("enter second no."))
s.add(s2)
s3 = int(input("enter third no."))
s.add(s3)
s4 = int(input("enter fourth no."))
s.add(s4)
s5 = int(input("enter fifth no."))
s.add(s5)
s6 = int(input("enter sixth no."))
s.add(s6)
s7 = int(input("enter seventh no."))
s.add(s7)
s8 = int(input("enter eighth no."))
s.add(s8)
print(s)